// const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

import { TsconfigPathsPlugin } from 'tsconfig-paths-webpack-plugin';

module.exports = {
    // Other Webpack configurations
    resolve: {
        plugins: [
            new TsconfigPathsPlugin({ configFile: './tsconfig.json' })
        ]
    },
    module: {
        rules: [
            {
                test: /\.(t|j)sx?$/,
                exclude: /node_modules/,
                use: "babel-loader",
            },
            {
                test: /.css$/,
                exclude: /\.vanilla\.css$/i,
                use: [MiniCssExtractPlugin.loader, "css-loader"],
            },
            {
                test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
                use: [
                    MiniCssExtractPlugin.loader,
                    {
                        loader: require.resolve("css-loader"),
                        options: {
                            url: false, // Required as image imports should be handled via JS/TS import statements
                        },
                    },
                ],
            },
        ],
    },
    plugins: [
        new CleanWebpackPlugin(),
        new VanillaExtractPlugin(),
        new MiniCssExtractPlugin(),
    ],
    optimization: {
        sideEffects: true,
        usedExports: true,
    },
};
